### ISSUE TITLE
When I try to use snippet, this extension stop typescript language server

### ISSUE THREAD

**Issue by pjb6510** [Yash-Singh1/stylex-vscode#1]
Thank you for making this extension. 
I'm enjoying to use styleX with this extension.
but I found this extension is making a issue.
When I try to use snippet, this extension stop typescript language server.

Could you check this issue please?

How to recreate: 

1. on .tsx file, try to use snippet (I tried to use `fc` (functional component))
2. check Code Helper (Plugin) CPU usage (90~100%)
3. disable this extension
4. check if the issue is solved.

https://github.com/Yash-Singh1/stylex-vscode/assets/57614769/078fe1af-9d19-4ac8-95e6-3a89c9fb4e9e

**Comment by Yash-Singh1** [comment]
Hi @pjb6510, thanks for creating this issue! I am currently diagnosing performance issues in the extension and these forms of detailed reports really help me understand how to reproduce these issues.

I just released a new version (`0.0.11`) that hopefully fixes this issue. Could you please check and confirm that this fixes the issue?

**Comment by pjb6510** [comment]
@Yash-Singh1 

Thank you for your quick solving!
I checked the issue has been fixed!!
👍👍👍
